[tool.poetry]
name = "xtns-pico"
version = "0.1.0"
description = ""
authors = ["loristns"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.2.2"
typer = "^0.12.1"
lightning = {extras = ["extra"], version = "^2.2.4"}
rich = "^13.7.1"
wandb = "^0.16.6"
datasets = "^2.18.0"
einops = "^0.8.0"
deepspeed = "^0.14.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[tool.poetry.group.experiments]
optional = true

[tool.poetry.group.experiments.dependencies]
ipykernel = "^6.29.4"
scikit-learn = "^1.4.2"
matplotlib = "^3.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
