[tool.poetry]
name = "xtns-pico"
version = "0.1.0"
description = ""
authors = ["loristns"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.2.2"
typer = "^0.12.1"
lightning = "^2.2.1"
deepspeed = "^0.14.0"
rich = "^13.7.1"
wandb = "^0.16.6"
datasets = "^2.18.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
