[tool.poetry]
name = "xtns-pico"
version = "0.1.0"
description = "Pico SLM"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
einops = "^0.8.0"
flash-attn = {url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu123torch2.4cxx11abiFALSE-cp311-cp311-linux_x86_64.whl"}
torch = {version = "^2.4.0", source = "torch"}
datasets = "^2.21.0"
typer = "^0.12.5"
safetensors = "^0.4.5"
triton = "^3.0.0"
accelerate = "^0.34.2"
deepspeed = "^0.15.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"