[tool.poetry]
name = "xtns-pico"
version = "0.1.0"
description = "Pico SLM"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
torch = {version = "2.5.0.dev20240826+cu121", allow-prereleases = true, source = "pytorch-nightly"}
einops = "^0.8.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.2"

[[tool.poetry.source]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
